# Generated by Django 3.0.8 on 2021-12-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='8112933041', editable=False, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('0', 'Pending'), ('1', 'Completed'), ('2', 'Canceled'), ('3', 'Waiting')], default='3', max_length=10)),
                ('level', models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters')], max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('admit_card', models.FileField(blank=True, null=True, upload_to='admit_card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_applications', to='applicant.ApplicantProfile')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_applications', to='institution.InstitutionProfile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_applications', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_applications', to='institution.InstitutionSubject')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': '1. Applications',
            },
        ),
    ]
