# Generated by Django 3.0.8 on 2021-12-29 16:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='Institute Name', max_length=255)),
                ('institute_city', models.CharField(default='Institute City', max_length=150)),
                ('institute_location', models.CharField(default='Institute Location', max_length=255)),
                ('institute_code', models.CharField(default='Institute Code', max_length=50)),
                ('application_fee', models.FloatField(default=0.0)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Both')], default='3', max_length=10)),
                ('institute_pic', models.ImageField(blank=True, null=True, upload_to='institution')),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_institute', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'InstitutionProfile',
                'verbose_name_plural': '1. InstitutionProfile',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_subscribers', to='institution.InstitutionProfile')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=250)),
                ('level', models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters'), ('3', 'Both')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_subjects', to='institution.InstitutionProfile')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', ckeditor.fields.RichTextField()),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_instructions', to='institution.InstitutionProfile')),
            ],
            options={
                'verbose_name': 'InstituteInstruction',
                'verbose_name_plural': '3. InstituteInstruction',
            },
        ),
        migrations.CreateModel(
            name='AdmissionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('level', models.CharField(choices=[('1', 'Bachelor'), ('2', 'Masters'), ('3', 'Bachelor & Masters')], default='3', max_length=50)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='institute_session', to='institution.InstitutionProfile')),
            ],
            options={
                'verbose_name': 'AdmissionSession',
                'verbose_name_plural': '2. AdmissionSession',
            },
        ),
    ]
